### PR TITLE
Add Installing Software Guide

### PR DESCRIPTION
**Pull request by Chris-Johnston**
Add a guide that explains how to install various software that may be useful for the event.

Also adds a link in the preparation checklist back to this new article. Need to fix the destination link before merging.

### CODE REVIEW

**Comment by Chris-Johnston** [comment]
@bpas247 Could use your input on what to add to the Java section.

**Comment by bpas247** [comment]
I have a [wiki](https://github.com/UWB-ACM/DiscordBot_Java/wiki/Setting-Up-Your-Environment) article under the DiscordBot_Java repository with information on how to set up your environment using Gradle, although Gradle isn't a Java-specific tool. What we could do is include information about:

- PMD
- FindBugs
- CheckStyle (not Java-specific)
- IntelliJ
- JUnit
- Gradle (Using above technologies)
- Integrating Travis CI with a Gradle repository

**Comment by Chris-Johnston** [comment]
Cool, I'll add information from that to this guide. I'm trying to avoid a wiki, because anyone can make changes without any review.

**Comment by bpas247** [comment]
You can "Restrict editing to collaborators only" for wikis, if you don't want the public to edit them. I might make that wiki article into an MD file somewhere on the DiscordBot_Java repo, or we can just include it here instead.

**Comment by Chris-Johnston** [comment]
My issue with restricting to only collaborators is that then nobody else (public) can suggest changes.

**Comment by Chris-Johnston** [comment]
I think that what we have is good enough to get a first revision in.

**Pull request merged**
